// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfXwoecJ_EiMCgdp2U4icuDF9tOMPDr8',
    appId: '1:1013473742284:web:c8b608003d8f31bd7ee169',
    messagingSenderId: '1013473742284',
    projectId: 'blindside-8e509',
    authDomain: 'blindside-8e509.firebaseapp.com',
    storageBucket: 'blindside-8e509.appspot.com',
    measurementId: 'G-7NW357E01E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGVsRbk2xUDg8zac-iARN2ACVFdqZNPo',
    appId: '1:1013473742284:android:a414271d540a6f637ee169',
    messagingSenderId: '1013473742284',
    projectId: 'blindside-8e509',
    storageBucket: 'blindside-8e509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UFAwqHJXqiwB030JC0kxg8c3GUgiZuw',
    appId: '1:1013473742284:ios:bb6d31f4f4ad59957ee169',
    messagingSenderId: '1013473742284',
    projectId: 'blindside-8e509',
    storageBucket: 'blindside-8e509.appspot.com',
    iosClientId: '1013473742284-2s277fd99lrmv4toc2cajbgl0obev567.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.blindside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UFAwqHJXqiwB030JC0kxg8c3GUgiZuw',
    appId: '1:1013473742284:ios:82b467e7114efe7a7ee169',
    messagingSenderId: '1013473742284',
    projectId: 'blindside-8e509',
    storageBucket: 'blindside-8e509.appspot.com',
    iosClientId: '1013473742284-aei434ujcsu1ffa6lopqg6ikjb9pf51q.apps.googleusercontent.com',
    iosBundleId: 'come.example.verygoodcore.blindside',
  );
}
